### ISSUE TITLE
裁剪手部数据进行分类的问题

### ISSUE THREAD

**Issue by geoyee** [Nanyi-Brigade/GBIM#10]
1. 裁减范围目视看起来有点问题，需要进行检查
2. 应该将阈值使用，对于阈值低的手势不进行采集裁剪（与现实保持同步）

**Comment by leaf59** [comment]
> 1. 裁减范围目视看起来有点问题，需要进行检查
> 2. 应该将阈值使用，对于阈值低的手势不进行采集裁剪（与现实保持同步）

已解决
